### ISSUE TITLE
Problema con Tests.

### ISSUE THREAD

**Issue by ycavodeassi** [obj1unq-2018s2/tp-cuatrimestral-jardon-solanes-cavodeassi#1]
**Tests**
Realizar, como mínimo, el siguiente test:

Crear un campeón con 50 puntos de vida y 15 de ataque.
Equiparlo con un anillo de Doran y un Tomo Amplificador.
Crear una Oleada de 10 minions con un plus de 5 puntos de daño.
Hacer que el campeón ataque a la oleada de minions y luego se desequipe el Tomo Amplificador.
**

> Probar que el campeón esta muerto tras haberse desequipado el tomo.

**

El campeón nunca puede morir cuenta con los bloqueos del tomo Amplificador y los atributos de vida al tener el anillo de doran equipado. Osea que ademas de los bloqueos los puntos de danio serian inferiores a los puntos de vida.

**Comment by npasserini** [comment]
Fijate mi mail del lunes 22 a las 21:42 tiene la respuesta a esta pregunta.

**Comment by ycavodeassi** [comment]
Perdón, no tengo el mail, tampoco en no deseados.

**Comment by npasserini** [comment]
¿No estás en la lista de la materia? Me preocupa eso, es un mecanismo de
comunicación oficial. Ojo porque puede haber anuncios importantes ahí.

De todas maneras, lo que tenés que hacer es esto:

Para actualizarse el enunciado en su workspace pueden hacer:
1) Tener un workspace limpio, es decir, commitear lo que tenemos.
2) Team -> "Pull ..."
3) "New Remote"
4) Llenar "remote name" con lo que ustedes quieran, por ejemplo
"enunciado", es sólo un nombre para ustedes.
5) Llenar URI con
https://github.com/obj1unq/tp-cuatrimestral-2018s2-liga-de-leyendas.git
6) Finalizar

Deberían ver una ventanita que dice "merged" (entre muchas cosas).
Y si ven el enunciado debería estar actualizado.
